server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/develop
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
    generate-ddl: true

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"

feign:
  request-url:
    # naver-band: "https://openapi.band.us"
    # mdnf: "http://localhost:8080"
    naver-band: "https://openapi.band.us"
    mdnf: "https://dnfm.nexon.com"

fcm:
  certification: "firebaseAccountKey.json"